# sample_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SampleApi
  # APIController
  class APIController < BaseController
    # TODO: type endpoint description here
    # @return [ItemsResponse] response from the API call.
    def get_a_list_of_items
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/items',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ItemsResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [ItemsRequest] body Required parameter: Example:
    # @return [void] response from the API call.
    def create_a_new_item(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/items',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end))
        .response(new_response_handler
                    .is_response_void(true))
        .execute
    end
  end
end
