# sample_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SampleApi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
